project_id = "tudyfisampfciwcijsyx"

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.reset-password]
verify_jwt = false

[functions.generate-quiz]
verify_jwt = true

[functions.get-current-affairs]
verify_jwt = false